version: "3.8"

services:
  mariadb:
    image: mariadb:11.4
    environment:
      MYSQL_ROOT_PASSWORD: "Vheh150630!"
      MYSQL_DATABASE: routereciptdb
      MYSQL_USER: reciptback
      MYSQL_PASSWORD: "rainbow77&&**"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  redis-bloom:
    image: redislabs/rebloom:latest
    restart: always

  fastapi:
    build: ./fastapi
    restart: unless-stopped

  springboot:
    build: .
    depends_on:
      - mariadb
      - redis-bloom
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/routereciptdb
      SPRING_DATASOURCE_USERNAME: reciptback
      SPRING_DATASOURCE_PASSWORD: "rainbow77&&**"
      SPRING_DATA_REDIS_HOST: redis-bloom
      SPRING_DATA_REDIS_PORT: 6379
      FASTAPI_BASE_URL: http://fastapi:8000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: unless-stopped

volumes:
  db_data:
