version: "3.8"

services:
  mariadb:
    image: mariadb:11.4
    environment:
      MYSQL_ROOT_PASSWORD: "Vheh150630!"
      MYSQL_DATABASE: routereciptdb
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"   # 팀 확인용 (선택)
    restart: always

  redis-bloom:
    image: redislabs/rebloom:latest
    restart: always

  fastapi-ai:
    build:
      context: ./fastapi-ai
      dockerfile: Dockerfile
    restart: unless-stopped

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - redis-bloom
      - fastapi-ai
    ports:
      - "8090:8090"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev

      # ===== DB =====
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/routereciptdb
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      # ===== Redis =====
      SPRING_DATA_REDIS_HOST: redis-bloom
      SPRING_DATA_REDIS_PORT: 6379

      # ===== AI =====
      AI_CATEGORY_URL: http://fastapi-ai:8000
    restart: unless-stopped

volumes:
  db_data:
