spring.application.name=RouteRecipt
server.port=8090
server.address=0.0.0.0

#secret propertie\u00ec\u0097\u0090\u00ec\u0084\u009c api key \u00eb\u00b6\u0088\u00eb\u009f\u00ac\u00ec\u0098\u00a4\u00ea\u00b8\u00b0
spring.config.import=optional:file:./config/secrets.properties


spring.datasource.driverClassName=org.mariadb.jdbc.Driver

spring.datasource.url=jdbc:mariadb://localhost:3306/routereciptdb
spring.datasource.username=root
spring.datasource.password=1111

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-statement-timeout=30
mybatis.configuration.jdbc-type-for-null=VARCHAR
mybatis.configuration.call-setters-on-nulls=true
mybatis.configuration.auto-mapping-unknown-column-behavior=WARNING

openai.api-key=${OPENAI_API_KEY}
openai.model=gpt-4.1-mini

openai.endpoint=https://api.openai.com/v1
openai.max-output-tokens=800
openai.timeout-ms=15000

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=1GB

clova.secret=${CLOVA_SECRET}
clova.url=${CLOVA_URL}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.data.redis.host=localhost
spring.data.redis.port=6379


logging.level.org.mybatis=DEBUG
logging.level.jdbc.sqlonly=DEBUG
logging.level.jdbc.resultset=DEBUG
logging.level.jdbc.audit=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE

receipt.upload.temp-dir=/app/uploads